export const DEFAULT_CONFIG = {
  ENVIRONMENTS: {
    DEVELOPMENT: 'development',
    PRODUCTION: 'production',
    TEST: 'test',
  },
  SHARD_TYPES: {
    NONE: 'none',
    MONTHLY: 'monthly',
    YEARLY: 'yearly',
  },
  SHARD_STRATEGIES: {
    SUFFIX: 'suffix',
    BUCKET_PARENT: 'bucket-parent',
  },
  SEARCH_MODES: {
    NONE: 'none',
    TOKEN_ARRAY: 'token-array',
    PREFIX: 'prefix',
    EXTERNAL: 'external',
  },
  BACKENDS: {
    SQL: 'sql',
    DATACONNECT: 'dataconnect',
    POSTGRES: 'postgres',
  },
  RULE_PRESETS: {
    AUTH: 'auth',
    OWNER: 'owner',
    OWNER_OR_ADMIN: 'ownerOrAdmin',
    ADMIN_ONLY: 'adminOnly',
    PUBLIC: 'public',
    NONE: 'none',
  },
  SYSTEM_FIELDS: [
    'id',
    'createdAt',
    'updatedAt',
    'createdBy',
    'updatedBy',
    'archivedAt',
    'deletedAt',
    'deletedBy',
    'isDeleted',
    '_searchText',
    '_searchTokens',
    '_searchPrefixes',
    'shardKey',
  ],
  ERROR_CODES: {
    UNKNOWN: 'UNKNOWN',
    INVALID_ID: 'INVALID_ID',
    INVALID_DATA: 'INVALID_DATA',
    INVALID_PAGE_SIZE: 'INVALID_PAGE_SIZE',
    INVALID_COLLECTION_DEFINITION: 'INVALID_COLLECTION_DEFINITION',
    COLLECTION_NOT_REGISTERED: 'COLLECTION_NOT_REGISTERED',
    UNKNOWN_FIELD: 'UNKNOWN_FIELD',
    REQUIRED_FIELD: 'REQUIRED_FIELD',
    INVALID_FIELD_TYPE: 'INVALID_FIELD_TYPE',
    READONLY_FIELD: 'READONLY_FIELD',
    IMMUTABLE_FIELD: 'IMMUTABLE_FIELD',
    ENUM_MISMATCH: 'ENUM_MISMATCH',
    QUERY_NOT_ALLOWED: 'QUERY_NOT_ALLOWED',
    INDEX_REQUIRED: 'INDEX_REQUIRED',
    SEARCH_NOT_CONFIGURED: 'SEARCH_NOT_CONFIGURED',
    NOT_FOUND: 'NOT_FOUND',
    PERMISSION_DENIED: 'PERMISSION_DENIED',
    UNAVAILABLE: 'UNAVAILABLE',
    DEADLINE_EXCEEDED: 'DEADLINE_EXCEEDED',
    ABORTED: 'ABORTED',
    ALREADY_EXISTS: 'ALREADY_EXISTS',
    FAILED_PRECONDITION: 'FAILED_PRECONDITION',
    INVALID_ARGUMENT: 'INVALID_ARGUMENT',
    INTERNAL: 'INTERNAL',
    RULES_GENERATION_FAILED: 'RULES_GENERATION_FAILED',
    INDEX_GENERATION_FAILED: 'INDEX_GENERATION_FAILED',
  },
  SAFE_PUBLIC_MESSAGES: {
    UNKNOWN: 'Something went wrong. Please try again.',
    INVALID_ID: 'The item reference is invalid.',
    INVALID_DATA: 'The provided information is invalid.',
    INVALID_PAGE_SIZE: 'The requested page size is invalid.',
    INVALID_COLLECTION_DEFINITION: 'This data model is not configured correctly.',
    COLLECTION_NOT_REGISTERED: 'This section is not available right now.',
    UNKNOWN_FIELD: 'One or more fields are not allowed.',
    REQUIRED_FIELD: 'Some required information is missing.',
    INVALID_FIELD_TYPE: 'One or more fields have the wrong format.',
    READONLY_FIELD: 'One or more fields cannot be changed.',
    IMMUTABLE_FIELD: 'One or more fields cannot be updated after creation.',
    ENUM_MISMATCH: 'One or more values are not allowed.',
    QUERY_NOT_ALLOWED: 'This request is not supported.',
    INDEX_REQUIRED: 'This request needs an index configuration update.',
    SEARCH_NOT_CONFIGURED: 'Search is not enabled for this section.',
    NOT_FOUND: 'The requested item was not found.',
    PERMISSION_DENIED: 'You do not have permission to perform this action.',
    UNAVAILABLE: 'The service is temporarily unavailable. Please try again.',
    DEADLINE_EXCEEDED: 'The request took too long. Please try again.',
    ABORTED: 'The action was interrupted. Please retry.',
    ALREADY_EXISTS: 'This item already exists.',
    FAILED_PRECONDITION: 'The request cannot be completed in the current state.',
    INVALID_ARGUMENT: 'The request contains invalid information.',
    INTERNAL: 'The action could not be completed right now.',
    RULES_GENERATION_FAILED: 'Rules could not be generated.',
    INDEX_GENERATION_FAILED: 'Indexes could not be generated.',
  },
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 200,
  DEFAULT_DATE_FIELD: 'createdAt',
  DEFAULT_SHARD_STRATEGY: 'suffix',
  DEFAULT_SHARD_METADATA_FIELD: 'shardKey',
  TOKEN_PREFIX_LIMIT: 12,
  SOFT_DELETE_FIELD: 'isDeleted',
  DELETED_AT_FIELD: 'deletedAt',
  DELETED_BY_FIELD: 'deletedBy',
  DEFAULT_BULK_STATUS_FIELD: 'status',
};

export const FIELD_TYPES = {
  STRING: 'string',
  NUMBER: 'number',
  BOOLEAN: 'boolean',
  ARRAY: 'array',
  OBJECT: 'object',
  TIMESTAMP: 'timestamp',
  REFERENCE: 'reference',
  ANY: 'any',
};
